name: hyperspectral-cnn-soil-estimation
channels:
- conda-forge
dependencies:
- python=3.9
- cudatoolkit=11.2
- cudnn=8.1.0
- pip
- pip:
  - tensorflow==2.10.1
  - pandas
  - Pillow
  - gdown
  - notebook
  - matplotlib
  - jupyter_http_over_ws
